### ISSUE TITLE
Travis builds b0rk3d

### ISSUE THREAD

**Issue by jedisct1** [facebookincubator/fizz#3]
Hi!

Looks like Travis builds do not currently work:

```
Traceback (most recent call last):
  File "/home/travis/build/jedisct1/fizz/build/fbcode_builder/make_docker_context.py", line 173, in <module>
    config['github_project'],
  File "/home/travis/build/jedisct1/fizz/build/fbcode_builder/make_docker_context.py", line 154, in make_docker_context
    dockerfile = builder.render(get_steps_fn(builder))
  File "/home/travis/build/jedisct1/fizz/build/fbcode_builder/fbcode_builder.py", line 136, in render
    .format(unused_options)
RuntimeError: Unused options: set([u'facebookincubator/fizz:local_repo_dir']) -- please check if you made a typo in any of them. Those that are truly not useful should be not be set so that this typo detection can be useful.
+docker_context_dir=
```

**Comment by siyengar** [comment]
We figured out the issue here and it's due to defaults being configured to the facebook org vs the facebookincubator org. Working on a fix.

**Comment by siyengar** [comment]
This "should" be fixed now

**Comment by jedisct1** [comment]
Thanks!
